project_name: "testDNAValidator"
framework_version: 1

account: "666196153281"
region: "us-east-1"
environment: "dev"
config:
  environment_vars:
    API_BODY_SIZE_LIMIT: "10485760‬"
    API_PARAMETER_LIMIT: "10000000000"
    API_TIME_UP: "60000"
    AWS_ACCOUNT_ID: "666196153281"
    DB_BANK4US: "BAAS.BANK4US"
    DB_INDEX_CATALOGUE: "GSI-index-03"
    DB_INDEX_REVERSE: "GSI-index-02"
    DB_INDEX_DATA: "GSI-index-01"
    DB_PENDING_TASKS: "BAAS.PENDING_TASK"
    DB_DEFAULT_THEME_ID: "DEFAULT"
    EXPIRED_DOCUMENTS: "3600"
    HOST_DB: "http://35.170.8.187:19200"
    INDEX_NAME_PROCESS: "process-status"
    NODE_ENV: "dev"
    PROJECT_NAME: "DexApp"
    ROUTE_DOCUMENTS_PROCESSES: $..NewDocuments
    STORAGE_DOCUMENTS: "doc-process"
    NODE_API_PORT: "3000"
    SECRET_KEY_JWT: "jwt/internalseed"
    DEFAULT_PAGINATION: "20"
    FUNCTIONAL_DOCUMENTATION: "enabled"
    PAGE_SIZE: "10"
    DOCUMENTS_MAX_SIZE: "52428800"

tags:
  Project: "DexApp"
  Environment: dev
