name: Node.js CI
on:
  push:
    branches:
      - main # Ajusta la rama a la que deseas que se aplique
  pull_request:
    branches:
      - main # Ajusta la rama a la que deseas que se aplique
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.18
      - run: npm install
      - run: npm test
